/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2020-12-14 08:30:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class writeForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/template/footer.jsp", Long.valueOf(1607824747014L));
    _jspx_dependants.put("/WEB-INF/template/link.jsp", Long.valueOf(1607824747012L));
    _jspx_dependants.put("/WEB-INF/template/header.jsp", Long.valueOf(1607824747016L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/reset.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/all.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/notosanskr.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/default.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/paginate.css\" />\r\n");
      out.write("<link rel=\"icon\" href=\"/favicon.png\"/>\r\n");
      out.write("<script src=\"/js/jquery.js\"></script>\r\n");
      out.write("<script src=\"/js/moment-with-locales.js\"></script>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/form.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<h1><a href=\"/\"><i class=\"fas fa-list\"></i> 코로나 확진자 리스트</a></h1>\r\n");
      out.write("\t</div><!-- //#header  -->\r\n");
      out.write("\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<h2><i class=\"fas fa-pencil-alt\"></i> 확진자 추가하기</h2>\r\n");
      out.write("\t<form method=\"post\" action=\"/write.bmj\">\r\n");
      out.write("\t\t<fildset>\r\n");
      out.write("\t\t\t<legend class=\"screen_out\">글쓰기 폼</legend>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label class=\"title\" for=\"place\">장소 이름</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input1\" name=\"place\"\r\n");
      out.write("\t\t\t\t placeholder=\"장소이름을 입력\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label class=\"title\" for=\"address\">주소</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input1\" name=\"address\"\r\n");
      out.write("\t\t\t\t placeholder=\"주소를 입력\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label class=\"title\" for=\"city\">시</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input2\" name=\"city\"\r\n");
      out.write("\t\t\t\t placeholder=\"시를 입력\"/>\r\n");
      out.write("\t\t\t\t<label class=\"title\" for=\"gu\">구</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input2\" name=\"gu\"\r\n");
      out.write("\t\t\t\t placeholder=\"구를 입력\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label class=\"title\" for=\"latitude\">위도</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input2\" name=\"latitude\"\r\n");
      out.write("\t\t\t\t placeholder=\"위도를 입력\"/>\r\n");
      out.write("\t\t\t\t<label class=\"title\" for=\"longititude\">경도</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input2\" name=\"longititude\"\r\n");
      out.write("\t\t\t\t placeholder=\"경도를 입력\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label class=\"title\" for=\"mask\">마스크여부</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input2\" name=\"mask\"\r\n");
      out.write("\t\t\t\t placeholder=\"M:착용 N:미착용\"/>\r\n");
      out.write("\t\t\t\t<label class=\"title\" for=\"num\">확진 순서</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input2\" name=\"num\"\r\n");
      out.write("\t\t\t\t placeholder=\"순서를 입력\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<span class=\"title\">시작시각</span>\r\n");
      out.write("\t\t\t\t<select class=\"input3 year\" name=\"startYear\"></select><span class=\"title-input3\">년</span>\r\n");
      out.write("\t\t\t\t<select class=\"input3 month\" name=\"startMonth\"></select><span class=\"title-input3\">월</span>\r\n");
      out.write("\t\t\t\t<select class=\"input3 date_d\" name=\"startDay\"></select><span class=\"title-input3\">일</span>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<span class=\"title\">종료시각</span>\r\n");
      out.write("\t\t\t\t<select class=\"input3 year\" name=\"endYear\"></select><span class=\"title-input3\">년</span>\r\n");
      out.write("\t\t\t\t<select class=\"input3 month\" name=\"endMonth\"></select><span class=\"title-input3\">월</span>\r\n");
      out.write("\t\t\t\t<select class=\"input3 date_d\" name=\"endDay\"></select><span class=\"title-input3\">일</span>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"btn_box\">\r\n");
      out.write("\t\t\t\t<button class=\"btn\" type=\"reset\"><i class=\"fas fa-retweet\"></i> 리 셋</button>\r\n");
      out.write("\t\t\t\t<button class=\"btn\" type=\"submit\"><i class=\"fas fa-pencil-alt\"></i> 글쓰기</button>\r\n");
      out.write("\t\t\t\t<a class=\"btn\" href=\"/index.jsp\"><i class=\"fa fa-arrow-left \"></i> 게시판으로</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fildset>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("</div><!--  //#content  -->\r\n");
      out.write("\t\t\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t&copy;2020 Corona.org\r\n");
      out.write("</div><!-- // #footer  -->\r\n");
      out.write("</div><!-- //#wrap  -->");
      out.write("\r\n");
      out.write("\t<script src=\"/js/create-date.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
